fix: turn hasura actions coin amount type to string
forbole/bdjuno pull request #332
Opened 2022-02-16 02:25 UTC by huichiaotsou

## Description

Closes: #325

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-02-16 11:08 UTC, MonikaCat requested changes
I think we can also update Coins object to `[]Coin` type in `Delegation` struct, can you add it pls?

2022-02-17 13:02 UTC, MonikaCat commented on cmd/actions/types/utils.go
> +func ConvertSdkCoins(s sdk.Coins) []Coin {
This seems a bit redundant. There are methods `NewDbDecCoin`, `NewDbDecCoins `, `NewDbCoin` 
 and `NewDbCoins` that convert the `Amount` value to string, can we use them instead?

2022-02-18 10:59 UTC, MonikaCat approved these changes

2022-02-18 11:17 UTC, MonikaCat approved these changes
tested, LGTM

2022-02-18 14:39 UTC, RiccardoM approved these changes
utACK

2022-02-18 14:40 UTC, merged