feat: store software upgrade plan and refresh data at upgrade height
forbole/bdjuno pull request #467
Opened 2022-09-15 14:36 UTC by huichiaotsou

## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-09-22 09:10 UTC, MonikaCat commented on modules/upgrade/module.go
> +// Module implements the consensus utils
```suggestion
// Module represents the x/upgrade module
```

2022-09-22 10:10 UTC, MonikaCat requested changes
@huichiaotsou Can you also add a handler to remove the software upgrade details from `software_upgrade_plan` table after the upgrade height has been passed?

2022-09-26 07:12 UTC, MonikaCat approved these changes
tested, LGTM

2022-10-04 21:39 UTC, RiccardoM approved these changes
LGTM, great job @huichiaotsou! :clap:

2022-10-04 21:40 UTC, merged